Added two problems of Codeforces
saumyasrivastava08/Important_Coding_Problems pull request #75
Opened 2021-09-30 18:32 UTC by rushendra910

-> Please merge this pull request under the tag 'hacktoberfest2021'

2021-09-30 18:40 UTC, saumyasrivastava08 requested changes
Add two more Questions then create PR.

2021-09-30 19:02 UTC, rushendra910 commented
> Add two more Questions then create PR.

@saumyasrivastava08 I have added two more solutions. Please merge pull request under the 'hacktoberfest2021-accepted' tag. Thank you

2021-09-30 19:19 UTC, rushendra910 commented
@saumyasrivastava08 I have made the requested changes.

2021-10-01 08:53 UTC, saumyasrivastava08 approved these changes

2021-10-01 08:53 UTC, merged